# Generated by Django 3.2.5 on 2022-07-15 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='noticia',
            new_name='cuerpo',
        ),
    ]
